package com.javatechie.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName ="Products")
@DynamoDBDocument
public class Product {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String code;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private int quantity;
    @DynamoDBAttribute
    private String availableDC;
}
